backend:
  name: git-gateway
  branch: main

local_backend: false

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "videos"
    label: "Videos"
    folder: "videos"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Tags", name: "tags", widget: "string", hint: "Comma separated tags"}
      - {label: "Thumbnail", name: "thumbnail", widget: "string", hint: "Paste thumbnail URL here"}
      - {label: "Video Embed", name: "video_embed", widget: "text", hint: "Paste your iframe embed code here"}
      - {label: "Featured", name: "featured", widget: "boolean", default: false}
      - {label: "Page", name: "page", widget: "select", options: [1, 2, 3, 4, 5], default: 1}
      - {label: "Position", name: "position", widget: "number", default: 1, hint: "Position on the page (1-5)"}
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", date_format: "YYYY-MM-DD", time_format: false}
      - {label: "Draft", name: "draft", widget: "boolean", default: false}

  - name: "site_settings"
    label: "Site Settings"
    files:
      - file: "site-config.json"
        label: "Site Configuration"
        name: "site_config"
        fields:
          - {label: "Site Title", name: "site_title", widget: "string", default: "DailyClips"}
          - {label: "Site Description", name: "site_description", widget: "text", default: "Hot videos updated daily"}
          - {label: "Banner Ad Code", name: "banner_ad_code", widget: "text", hint: "Paste your banner ad script here"}
          - {label: "Popunder Ad Code", name: "popunder_ad_code", widget: "text", hint: "Paste your popunder ad script here"}
          - {label: "Videos Per Page", name: "videos_per_page", widget: "number", default: 5}
          - {label: "Enable Search", name: "enable_search", widget: "boolean", default: true}
          - {label: "Enable Pagination", name: "enable_pagination", widget: "boolean", default: true}
